### ISSUE TITLE
Create a FIDO / U2F compatible firmware

### ISSUE THREAD

**Issue by mithro** [im-tomu/tomu-samples#3]
- https://github.com/yohanes/teensy-u2f (but see http://hackaday.com/2015/11/14/turning-a-teensy-into-a-better-u2f-key/)
- https://github.com/kmackay/micro-ecc - A small and fast ECDH and ECDSA implementation for 8-bit, 32-bit, and 64-bit processors.
- https://fidoalliance.org/specifications/overview/

**Comment by mithro** [comment]
https://github.com/conorpp/u2f-zero

**Comment by mithro** [comment]
https://github.com/Nitrokey

**Comment by mithro** [comment]
https://github.com/Nitrokey/nitrokey-start-firmware

**Comment by mithro** [comment]
http://www.fsij.org/category/gnuk.html

**Comment by mithro** [comment]
https://sourceforge.net/projects/skce/files/v2-Build124/

**Comment by mithro** [comment]
https://github.com/google/u2f-ref-code

**Comment by mithro** [comment]
https://github.com/avivgr/stm32-u2f

**Comment by pwarren** [comment]
I'll be working on this off and on over February, hope to have delivered by March 1st!

**Comment by pwarren** [comment]
Well, my tomu seems to be toast. Never did get it programmed with my Pi, and the Pi is now non-functional :(

I've attempted with an ST-LinkV2 dongle, but still fails.  So, I won't be able to get much done I'm sorry :(

**Comment by mithro** [comment]
@pwarren I can send you another one if email me your address.

**Comment by thearkadia** [comment]
Hey @pwarren any update on if you will still be working on this? if you still need a pi or a new Tomu I'm willing to chip in to help development continue.

**Comment by mithro** [comment]
I sent @pwarren a couple more Tomu boards, so he doesn't have any excuse not to do the work now :-P

I believe @joshgoes made have made some progress. He mentioned being able to get debugging output via usb-serial and seem to have working Fido compatible escriptors?

**Comment by thearkadia** [comment]
@mithro great! Has there been any updates since he recieved them? If I were to make or buy a tomu board could I already use it as a u2f device?

**Comment by pwarren** [comment]
I've received the new boards, and already blown up one of them, I think my USB ports are no good, I have found my old USB 2.0 hub, which so far hasn't damaged the working one.

Apart from that, I've had other priorities I'm sorry. I hope to be getting back into it mid July.

**Comment by gl-sergei** [comment]
Hi. I implemented fully working u2f token for stm32f103 controller using chopstx library and ECC implementation taken from gnuk (GPLv3+ code). It runs nice on Maple Mini. It passes tests from u2f-ref-code and works well with google, github and every other service I tried it on. Since chopstx supports MKL27Z256 as well, it should be easy to run this code on Tomu+. I am going to add support for hardware ECC with ATECC508A, but since I have no device it will take me a while to build one :) Would you guys be interested to run this project on Tomu+?

**Comment by mithro** [comment]
Hi @gl-sergei,

The Tomu+ is currently on hold until we have the Tomu working. What is a Maple Mini?

Do you think that you could port the stuff to the EFM32HG309? Looks like the STM32F103 is a ARM Cortex-M3 while the EFM32HG309 is an ARM Cortex-M0+ board and from what I can see Chopstx supports M0+ devices.

From http://www.fsij.org/category/gnuk.html
> Chopstx is an RT thread library for STM32F103 (ARM Cortex-M3), STM32F030 (ARM Cortex-M0), and MKL27Z (ARM Cortex-M0plus).

I would happily send you some boards if you wanted to do that?

Tim 'mithro' Ansell

**Comment by gl-sergei** [comment]
Hi @mithro,

Maple Mini is stm32f103 board developed by Leaflabs https://www.leaflabs.com/maple/. It is nice for prototyping and debugging, and its clones are easily available.

I think Chopstx can be ported to EFM32HG309 with little effort and I would happily do that. I don't have any EFM32 boards at hand, but looks like I can start with Qemu. How can I contact you to discuss the details about getting the boards?

**Comment by mithro** [comment]
You can email me at mithro@mithis.com or find me on IRC at irc://irc.freenode.net/#tomu

**Comment by mithro** [comment]
This now exists! See https://groups.google.com/forum/#!topic/tomu-discuss/CQzDdk2Vy9M and https://github.com/im-tomu/chopstx/tree/efm32/u2f

**Comment by mithro** [comment]
Thanks for all your work @gl-sergei !
