### ISSUE TITLE
Move the SDK download stuff to the top directory

### ISSUE THREAD

**Issue by mithro** [im-tomu/tomu-samples#8]
So it can be shared between all the sample code.

**Comment by dennisdegreef** [comment]
Is there any place to put it outside the project directory as well? I could implement that in https://github.com/im-tomu/tomu-samples/pull/14 and not 'polute' the source repository with it :)

If so, that image can be used for any tomu project, which is quite nice.

**Comment by mithro** [comment]
It's pretty normal to have a "build" or similar directory with things like this in it. (And then `.gitignore` the whole directory.)

Putting stuff outside the directory is a bit fraught with danger?

**Comment by mithro** [comment]
Fixed in https://github.com/im-tomu/tomu-samples/pull/18
